tests:
    stage: test
    image: registry.gitlab.com/craigbarnes/container-lua-testing/image
    script:
        - make -j`nproc` local-libgumbo
        - make build-all USE_LOCAL_LIBGUMBO=1 DEBUG=1
        - make check-all USE_LOCAL_LIBGUMBO=1
#        - make clean check-luarocks-make LUAROCKS=luarocks-5.3
#        - make check-luarocks-build LUAROCKS=luarocks-5.3
        - make coverage.txt USE_LOCAL_LIBGUMBO=1
        - sed -n '/^File  *Hits .*Coverage$/,/^Total.*%$/p' coverage.txt
        - luacov-coveralls-5.3 -t "$COVERALLS_TOKEN"

test-pages:
    stage: test
    image: quay.io/craigbarnes/pandoc
    script:
        - git fetch --tags
        - make -j`nproc` docs dist
        - make check-dist

pages:
    stage: deploy
    image: quay.io/craigbarnes/pandoc
    artifacts: {paths: [public]}
    only: [master]
    script:
        - git fetch --tags
        - make -j`nproc` docs dist
        - make check-dist
