stages: [test, dist]

test:debian:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/lua-testing
    script:
        - export MAKEFLAGS="-j$(mk/nproc.sh) -Otarget"
        - make build-all DEBUG=1
        - make check-all check-luajit

        - make clean-obj
        - make rockspecs
        - luarocks-5.3 make gumbo-*.53-1.rockspec
        - luarocks-5.2 make gumbo-*.52-1.rockspec
        - luarocks-5.1 make gumbo-*.51-1.rockspec
        - lua5.3 -lluarocks.loader -e 'require "gumbo"'
        - lua5.2 -lluarocks.loader -e 'require "gumbo"'
        - lua5.1 -lluarocks.loader -e 'require "gumbo"'

        - make clean-obj
        - make coverage.txt
        - sed -n '/^File  *Hits .*Coverage$/,/^Total.*%$/p' coverage.txt
        - luacov-coveralls-5.3 -t "$COVERALLS_TOKEN"

test:alpine:
    stage: test
    image: alpine:3.6
    script:
        - apk --update add make gcc binutils pkgconf
          libc-dev lua5.3-dev lua5.2-dev lua5.1-dev
        - export MAKEFLAGS="-j$(mk/nproc.sh) -Otarget"
        - make build-all DEBUG=1
        - make check-all

pages-test:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/pandoc
    except: [master]
    script:
        - git fetch --tags
        - make -j"$(mk/nproc.sh)" docs dist
        - make check-dist

pages:
    stage: dist
    image: registry.gitlab.com/craigbarnes/dockerfiles/pandoc
    artifacts: {paths: [public]}
    only: [master]
    script:
        - git fetch --tags
        - make -j"$(mk/nproc.sh)" docs dist
        - make check-dist
