tests:
    image: craigbarnes/lua-testing-extra
    script:
        - make -j4 local-libgumbo
        - make check-pkgconfig USE_LOCAL_LIBGUMBO=1

pages:
    image: craigbarnes/pandoc
    artifacts: {paths: [public]}
    only: [master]
    script:
        - git fetch --tags
        - make -j4 docs dist check-dist
