tests:
    stage: test
    image: quay.io/craigbarnes/lua-testing-extra
    script:
        - make -j`nproc` local-libgumbo
        - make check-all USE_LOCAL_LIBGUMBO=1
#        - make clean check-luarocks-make LUAROCKS=luarocks-5.3
#        - make check-luarocks-build LUAROCKS=luarocks-5.3
        - make coverage.txt USE_LOCAL_LIBGUMBO=1
        - sed -n '/^File  *Hits .*Coverage$/,/^Total.*%$/p' coverage.txt
        - luacov-coveralls-5.3 -t "$COVERALLS_TOKEN"

pages:
    stage: deploy
    image: quay.io/craigbarnes/pandoc
    artifacts: {paths: [public]}
    only: [master]
    script:
        - git fetch --tags
        - make -j`nproc` docs dist
        - make check-dist
