test:debian:dynamic:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/lua-testing
    script:
        - apt-get update
        - apt-get install -qy libgumbo-dev
        - export MAKEFLAGS="-j$(mk/nproc.sh)"
        - make build-all DEBUG=1
        - make --output-sync=line check-all

test:debian:static:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/lua-testing-extra
    script:
        - export MAKEFLAGS="-j$(mk/nproc.sh)" USE_LOCAL_LIBGUMBO=1
        - make local-libgumbo
        - make build-all DEBUG=1
        - make --output-sync=line check-all
#        - make clean check-luarocks-make LUAROCKS=luarocks-5.3
#        - make check-luarocks-build LUAROCKS=luarocks-5.3
        - make coverage.txt
        - sed -n '/^File  *Hits .*Coverage$/,/^Total.*%$/p' coverage.txt
        - luacov-coveralls-5.3 -t "$COVERALLS_TOKEN"

test:alpine:static:
    stage: test
    image: alpine:3.6
    script:
        - apk --update add make gcc binutils pkgconf curl gzip tar
          g++ autoconf automake libtool
          libc-dev lua5.3-dev lua5.2-dev lua5.1-dev
        - export MAKEFLAGS="-j$(mk/nproc.sh)" USE_LOCAL_LIBGUMBO=1
        - make local-libgumbo
        - make build-all DEBUG=1
        - make --output-sync=line check-lua53 check-lua52 check-lua51

pages-test:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/pandoc
    except: [master]
    script:
        - git fetch --tags
        - make -j"$(mk/nproc.sh)" docs dist
        - make check-dist

pages:
    stage: deploy
    image: registry.gitlab.com/craigbarnes/dockerfiles/pandoc
    artifacts: {paths: [public]}
    only: [master]
    script:
        - git fetch --tags
        - make -j"$(mk/nproc.sh)" docs dist
        - make check-dist
