tests:
    image: craigbarnes/lua-testing
    script:
        - apt-get update
        - apt-get install -qy g++ autoconf automake libtool
        - make local-libgumbo
        - make check-pkgconfig USE_LOCAL_LIBGUMBO=1

pages:
    image: debian:stretch
    artifacts: {paths: [public]}
    only: [master]
    script:
        - apt-get update
        - apt-get install -qy make pandoc
        - make docs
