language: c
sudo: false
branches: {only: master}
os: [linux, osx]
compiler: [clang, gcc]
before_script:
    - make -j`nproc` prep
script:
    - make print-vars USERVARS='CC LIBFLAGS'
    - make check-lua-all
