language: c
sudo: required
os: [linux]
compiler: [clang, gcc]
install:
    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt-get update -qq
    - sudo apt-get -y install lua5.2 lua5.1 liblua5.2-dev liblua5.1-dev cmake
script:
    - export VERBOSE=1
    - make -j"$(nproc)" build-lua52 build-lua51 V=1
    - make check-lib check-lua52 check-lua51
    - make clean
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j"$(nproc)" VERBOSE=1
    - cd ..
    - cp build/parse.so gumbo/
    - lua runtests.lua
