language:        c
branches:        {only: master}

os:              [linux, osx]
compiler:        [clang, gcc]
env:             [LUA_PC=lua5.1, LUA_PC=lua5.2, LUA_PC=luajit]

before_install:  make -f .travis.mk before_install
install:         make -f .travis.mk install
script:          make -f .travis.mk script
