language: c
sudo: false
branches: {only: master}
os: [linux, osx]
compiler: [clang, gcc]
before_script: make -j8 prep
script:
    - make env USERVARS='CC LDFLAGS'
    - make check-lua-all LUA_PC=none
