language: c
sudo: false
branches: {only: master}
os: [linux, osx]
compiler: [clang, gcc]
before_script:
    - make -j8 prep
    - luarocks-2.2.2/installation/bin/luarocks install luacov-coveralls
script:
    - make print-vars USERVARS='CC LDFLAGS'
    - make check-lua-all
    - make luacov-stats
after_success:
    - luarocks-2.2.2/installation/bin/luacov-coveralls -t "$COVERALLS_TOKEN"
