shallow_clone: true

environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2 --compat none"
  - LUA: "lua 5.3 --compat none"
  - LUA: "luajit 2.0"
  - LUA: "luajit 2.1"

matrix:
  fast_finish: true

install:
  - set PATH=%CD%\env\bin;C:\Python27\Scripts;%PATH%
  - pip install hererocks
  - hererocks env --%LUA% -rlatest
  - source env/bin/activate

build_script:
- luarocks make

test_script:
- cd "%APPVEYOR_BUILD_FOLDER%"
- lua runtests.lua
